defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5

development:
  <<: *defaults
  database: nl_develop
  username: bom

test: &test
  <<: *defaults
  database: nl_test
  username: bom